global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus se scrapea a s√≠ mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # sport-api
  - job_name: 'sport-api'
    static_configs:
      - targets: ['sport-server-staging.up.railway.app']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # sport-logic  
  - job_name: 'sport-logic'
    static_configs:
      - targets: ['sport-logic-staging.up.railway.app']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # event-service
  - job_name: 'event-service'
    static_configs:
      - targets: ['event-service-staging.up.railway.app']
    metrics_path: '/metrics'
    scrape_interval: 15s
